# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

python:
   version: 3.9
   install:
      - requirements: doc/requirements.txt

formats: []
